apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: app
    repoURL: https://github.com/jithunarayanan/gitops.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
